apiVersion: v1
kind: Secret
metadata:
  name: vault-external-tls-secret
  namespace: tanzu-system-ingress
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDlTCCAxygAw.......
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMG.........
    -----END PRIVATE KEY-----
