apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-test-sa
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: vault-agent-test
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'app-role'
    vault.hashicorp.com/agent-inject-secret-config.txt: 'secret/data/config'
    vault.hashicorp.com/tls-skip-verify: 'true'
    vault.hashicorp.com/agent-run-as-user: '1000'
    vault.hashicorp.com/agent-run-as-group: '1000'
spec:
  serviceAccountName: vault-test-sa
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: alpine
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL